---
title: "Thermocouple and Model Data"
author: "Brianne"
date: "2/23/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "C:/Users/Brianne/Documents/Simulated-Burn/")
```

Load Libraries 
```{r, echo = FALSE}
library(tidyverse)
library(plotly)
library(htmlwidgets)
```

Load the Data
```{r}

data <- read.csv("data/thermocouple_actualdata.csv")
data$time <- data$ï..Time
data$Depth <- as.factor(data$Depth)

new.df <- na.omit(data)

new.df <- new.df %>%  group_by(Depth, time, Type, Temperature, ID) %>% summarize(Mean_Temp = mean(Temperature.1))
```

Plot for Bare 450 with the model 450
```{r, echo = FALSE}
bare450 <- ggplot(new.df %>% filter(Temperature == "450", Mean_Temp >0, time < 60, Type != "BSC"), aes(x = time, y = Mean_Temp, color = Depth)) + geom_point(alpha = 0.5, size = 0.3)

ggplotly(bare450)

```

Plot for Bare 600 with the model 600
```{r, echo = FALSE}
bare600 <- ggplot(new.df %>% filter(Temperature == "600", Mean_Temp >0, time < 60, Type != "BSC"), aes(x = time, y = Mean_Temp, color = Depth)) + geom_point(alpha = 0.5, size = 0.3)

ggplotly(bare600)

```

Plot for BSC 450 with the model 450
```{r}
bsc450 <- ggplot(new.df %>% filter(Temperature == "450", Mean_Temp >0, time < 60, Type != "Bare"), aes(x = time, y = Mean_Temp, color = Depth)) + geom_point(alpha = 0.5, size = 0.3)


ggplotly(bsc450)

```

Plot for BSC 600 with the model 600
```{r}
bsc600 <- ggplot(new.df %>% filter(Temperature == "600", Mean_Temp >0, time < 60, Type != "Bare"), aes(x = time, y = Mean_Temp, color = Depth)) + geom_point(alpha = 0.5, size = 0.3)

ggplotly(bsc600)

```
